/**
 * Build HEIF files from scratch, so the reader can be tested against
 * containers whose every field is known.
 *
 * Deliberately not built by encoding a real photograph. Fixtures generated
 * from somebody's camera roll cannot be committed to a public repository, and
 * a fixture that has to be regenerated by a tool nobody has installed is a
 * test that quietly stops running. Everything here is assembled byte by byte
 * from two small constants, so the suite works on a clean checkout with
 * nothing installed but the dev dependencies.
 *
 * The tile payload and decoder configuration below came from a 64 by 64
 * gradient encoded with libheif's `heif-enc`. They carry no photograph. The
 * tile bytes are never decoded by these tests: a fake tile decoder stands in
 * for the platform, because what is under test is the container, not HEVC.
 */

const HVCC_BASE64 =
	'AQNwAAAAAAAAAAAAHvAA/P34+AAADwNgAAEAGEABDAH//wNwAAADAJAAAAMAAAMAHroCQGEAAQApQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbqrprm4CGgwIAAAAyAAAADAIRiAAEABkQBwXPBiQ==';

const TILE_BASE64 =
	'AAAAVigBrxMhd8dA9SGfg0wr/NwPfmyzgqGwltunRpyL5i+yYO4nQM6Yeb6awJy9upoNppSZfD7pdwF4+OFgrFtUPauU06USOeop12H2LJLZKt3QrxwAQQ54';

function fromBase64(text: string): Uint8Array {
	return Uint8Array.from(Buffer.from(text, 'base64'));
}

export const SAMPLE_HVCC = fromBase64(HVCC_BASE64);
export const SAMPLE_TILE = fromBase64(TILE_BASE64);

function concat(parts: readonly Uint8Array[]): Uint8Array {
	let total = 0;
	for (const part of parts) total += part.length;
	const out = new Uint8Array(total);
	let at = 0;
	for (const part of parts) {
		out.set(part, at);
		at += part.length;
	}
	return out;
}

function u8(...values: number[]): Uint8Array {
	return Uint8Array.from(values);
}

function u16(value: number): Uint8Array {
	return u8((value >> 8) & 0xff, value & 0xff);
}

function u32(value: number): Uint8Array {
	return u8((value >>> 24) & 0xff, (value >>> 16) & 0xff, (value >>> 8) & 0xff, value & 0xff);
}

function ascii(text: string): Uint8Array {
	return Uint8Array.from([...text].map((c) => c.charCodeAt(0)));
}

function box(type: string, ...payload: Uint8Array[]): Uint8Array {
	const body = concat(payload);
	return concat([u32(body.length + 8), ascii(type), body]);
}

function fullBox(
	type: string,
	version: number,
	flags: number,
	...payload: Uint8Array[]
): Uint8Array {
	return box(
		type,
		u8(version, (flags >> 16) & 0xff, (flags >> 8) & 0xff, flags & 0xff),
		...payload,
	);
}

export interface HeifFixtureOptions {
	/** Grid shape. One by one produces a plain untiled image instead of a grid. */
	readonly columns?: number;
	readonly rows?: number;
	readonly tileSize?: number;
	/** The image's real size, which is normally smaller than the padded grid. */
	readonly width?: number;
	readonly height?: number;
	readonly rotation?: 0 | 90 | 180 | 270;
	readonly mirror?: 'none' | 'horizontal' | 'vertical';
	/** Colour primaries as H.273 numbers. 12 is Display P3, 1 is BT.709. */
	readonly primaries?: number;
	/** Add a hidden `tmap` item, as an HDR photograph carries. */
	readonly gainMap?: boolean;
	/** Attach an EXIF item with this payload, starting at its TIFF header. */
	readonly exif?: Uint8Array;
	/** Declare a grid whose tiles do not cover its stated size. */
	readonly underCoveredGrid?: boolean;
}

/**
 * Assemble a HEIF file.
 *
 * The grid descriptor is placed in `idat` and located with construction method
 * 1, which is what Apple does and what a reader that assumes method 0 gets
 * wrong.
 */
export function buildHeif(options: HeifFixtureOptions = {}): Uint8Array {
	const columns = options.columns ?? 2;
	const rows = options.rows ?? 2;
	const tileSize = options.tileSize ?? 64;
	const tiled = columns > 1 || rows > 1;
	const width =
		options.width ?? (options.underCoveredGrid ? columns * tileSize + 8 : columns * tileSize - 8);
	const height =
		options.height ?? (options.underCoveredGrid ? rows * tileSize + 8 : rows * tileSize - 4);

	const tileCount = columns * rows;
	const primaryId = 1;
	// Untiled, the single image is itself the primary item. Tiled, the primary
	// is the grid and the tiles sit behind it.
	const tileIds = tiled ? Array.from({ length: tileCount }, (_, i) => i + 2) : [primaryId];
	const gainMapId = primaryId + tileCount + 1;
	const exifId = gainMapId + 1;

	/* ── Item information ─────────────────────────────────────────── */

	const infes: Uint8Array[] = [];
	if (tiled) {
		infes.push(fullBox('infe', 2, 0, u16(primaryId), u16(0), ascii('grid'), u8(0)));
	}
	for (const id of tileIds) {
		infes.push(fullBox('infe', 2, tiled ? 1 : 0, u16(id), u16(0), ascii('hvc1'), u8(0)));
	}
	if (options.gainMap) {
		infes.push(fullBox('infe', 2, 1, u16(gainMapId), u16(0), ascii('tmap'), u8(0)));
	}
	if (options.exif) {
		infes.push(fullBox('infe', 2, 0, u16(exifId), u16(0), ascii('Exif'), u8(0)));
	}
	const iinf = fullBox('iinf', 0, 0, u16(infes.length), ...infes);

	/* ── Properties ───────────────────────────────────────────────── */

	const properties: Uint8Array[] = [
		fullBox('ispe', 0, 0, u32(tileSize), u32(tileSize)), // 1: tile size
		box('hvcC', SAMPLE_HVCC), // 2
		fullBox('ispe', 0, 0, u32(width), u32(height)), // 3: image size
		box('colr', ascii('nclx'), u16(options.primaries ?? 1), u16(13), u16(6), u8(0x80)), // 4
	];
	let next = 5;
	let rotationIndex = 0;
	let mirrorIndex = 0;
	if (options.rotation) {
		properties.push(box('irot', u8((options.rotation / 90) & 0x03)));
		rotationIndex = next;
		next += 1;
	}
	if (options.mirror && options.mirror !== 'none') {
		properties.push(box('imir', u8(options.mirror === 'horizontal' ? 0 : 1)));
		mirrorIndex = next;
		next += 1;
	}
	const ipco = box('ipco', ...properties);

	const associations: Uint8Array[] = [];
	const primaryProperties = tiled
		? [3, 4, rotationIndex, mirrorIndex].filter((n) => n > 0)
		: // Untiled, the item's own ispe is the image size, which is what a real
			// single-image HEIC records. Associating the tile-size one instead
			// would make the fixture disagree with every file in the wild.
			[3, 2, 4, rotationIndex, mirrorIndex].filter((n) => n > 0);
	associations.push(u16(primaryId), u8(primaryProperties.length), u8(...primaryProperties));
	for (const id of tiled ? tileIds : []) {
		// Tiles carry their own size and the decoder configuration. Deliberately
		// not the rotation: in a real file that lives on the grid, and a reader
		// that took it from a tile would rotate every tile individually.
		associations.push(u16(id), u8(2), u8(1, 2));
	}
	const ipma = fullBox('ipma', 0, 0, u32(tiled ? tileCount + 1 : 1), ...associations);
	const iprp = box('iprp', ipco, ipma);

	/* ── References ───────────────────────────────────────────────── */

	const referenceBoxes: Uint8Array[] = [];
	if (tiled) {
		referenceBoxes.push(box('dimg', u16(primaryId), u16(tileIds.length), ...tileIds.map(u16)));
	}
	if (options.exif) {
		referenceBoxes.push(box('cdsc', u16(exifId), u16(1), u16(primaryId)));
	}
	const iref = referenceBoxes.length > 0 ? fullBox('iref', 0, 0, ...referenceBoxes) : undefined;

	/* ── Payloads ─────────────────────────────────────────────────── */

	// The grid descriptor: version, flags, rows - 1, columns - 1, then the
	// output size at 16 bits because the flag's low bit is clear.
	const gridDescriptor = concat([u8(0, 0, rows - 1, columns - 1), u16(width), u16(height)]);
	const idat = tiled ? box('idat', gridDescriptor) : undefined;

	const payloads: Uint8Array[] = tileIds.map(() => SAMPLE_TILE);
	if (options.gainMap) payloads.push(SAMPLE_TILE);
	if (options.exif) payloads.push(concat([u32(0), options.exif]));

	/* ── Locations ────────────────────────────────────────────────── */
	//
	// Written twice: once with a placeholder base offset to learn how long the
	// meta box is, then again once the real position of mdat is known. The
	// alternative is arithmetic that has to be redone every time a box is
	// added to this builder.

	const buildIloc = (mdatStart: number): Uint8Array => {
		const entries: Uint8Array[] = [];
		if (tiled) {
			// Construction method 1: the extent is an offset into idat.
			entries.push(u16(primaryId), u16(1), u16(0), u16(1), u32(0), u32(gridDescriptor.length));
		}
		let at = mdatStart;
		const located = tiled ? tileIds : tileIds;
		for (const _id of located) {
			entries.push(u16(_id), u16(0), u16(0), u16(1), u32(at), u32(SAMPLE_TILE.length));
			at += SAMPLE_TILE.length;
		}
		if (options.gainMap) {
			entries.push(u16(gainMapId), u16(0), u16(0), u16(1), u32(at), u32(SAMPLE_TILE.length));
			at += SAMPLE_TILE.length;
		}
		if (options.exif) {
			const length = 4 + (options.exif as Uint8Array).length;
			entries.push(u16(exifId), u16(0), u16(0), u16(1), u32(at), u32(length));
			at += length;
		}
		// offset_size 4, length_size 4, base_offset_size 0, index_size 0. With no
		// base offset there is no base offset field, so a version 1 entry is
		// item id, construction method, data reference index, extent count,
		// then the extents. An extra field here shifts the extent count onto
		// the wrong bytes and every later item reads as garbage.
		const count =
			(tiled ? 1 : 0) + tileIds.length + (options.gainMap ? 1 : 0) + (options.exif ? 1 : 0);
		return fullBox('iloc', 1, 0, u8(0x44), u8(0x00), u16(count), ...entries);
	};

	const hdlr = fullBox('hdlr', 0, 0, u32(0), ascii('pict'), u32(0), u32(0), u32(0), u8(0));
	const pitm = fullBox('pitm', 0, 0, u16(primaryId));
	const ftyp = box('ftyp', ascii('heic'), u32(0), ascii('mif1'), ascii('heic'));

	const metaOf = (iloc: Uint8Array): Uint8Array =>
		fullBox(
			'meta',
			0,
			0,
			hdlr,
			pitm,
			iinf,
			...(iref ? [iref] : []),
			iprp,
			iloc,
			...(idat ? [idat] : []),
		);

	const probe = metaOf(buildIloc(0));
	const mdatStart = ftyp.length + probe.length + 8;
	const meta = metaOf(buildIloc(mdatStart));

	return concat([ftyp, meta, box('mdat', ...payloads)]);
}

/** A tile decoder that fills each tile with a colour derived from its index. */
export function fakeTileDecoder(): import('../../src/heif/assemble.js').TileDecoder {
	return async (_config, tiles) =>
		tiles.map((tile, index) => {
			const data = new Uint8ClampedArray(tile.width * tile.height * 4);
			for (let i = 0; i < data.length; i += 4) {
				data[i] = (index * 40) % 256;
				data[i + 1] = (index * 70) % 256;
				data[i + 2] = (index * 110) % 256;
				data[i + 3] = 255;
			}
			return {
				data,
				width: tile.width,
				height: tile.height,
				colourSpace: 'srgb' as const,
				hasAlpha: false,
			};
		});
}
